In [1]:
import numpy as np
from sklearn.datasets import fetch_openml

# Q1

In [2]:
X, y = fetch_openml("mnist_784", version=1, return_X_y=True)

In [3]:
X = X.to_numpy()
y = y.to_numpy()

In [4]:
print(X.shape)
print(y.shape)

(70000, 784)
(70000,)


# Q2

In [5]:
y[2022]

'2'

In [6]:
X[2022].mean()

27.761479591836736

In [7]:
np.count_nonzero(X[2022] == 0)

643

In [8]:
np.unique(X[2022], return_counts=True)

(array([  0.,   1.,   2.,   3.,   6.,  10.,  11.,  14.,  18.,  20.,  27.,
         29.,  31.,  36.,  38.,  43.,  48.,  53.,  57.,  60.,  64.,  65.,
         71.,  72.,  73.,  78.,  79.,  81.,  84.,  87.,  89.,  99., 100.,
        108., 109., 119., 131., 133., 137., 138., 141., 149., 151., 153.,
        155., 169., 170., 175., 176., 185., 188., 198., 201., 205., 206.,
        207., 209., 218., 223., 224., 225., 227., 229., 230., 237., 239.,
        240., 242., 245., 246., 249., 251., 253., 254.]),
 array([643,   2,   1,   1,   5,   2,   1,   3,   1,   1,   1,   2,   1,
          1,   1,   1,   3,   1,   1,   4,   2,   3,   1,   1,   1,   1,
          2,   1,   1,   1,   1,   4,   1,   2,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   2,   1,   1,   1,   1,   1,   1,
          1,   2,   2,   3,   1,   1,   2,   1,   1,   4,   1,   2,   1,
          2,   2,   2,   1,   1,   2,   1,   2,  32]))

# Q3

In [9]:
X_train, y_train =  X[:10000], y[:10000]
X_test, y_test = X[10000:12000], y[10000:12000]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(10000, 784) (10000,)
(2000, 784) (2000,)


In [10]:
len(np.unique(y_train))

10

In [11]:
np.count_nonzero(y_train == "6")

1014

In [12]:
np.count_nonzero(y_train == "9")


978

In [13]:
len(np.unique(y_test))

10

In [14]:
np.unique(y_test, return_counts=True)

(array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype=object),
 array([205, 224, 185, 196, 204, 185, 194, 209, 183, 215]))

# Q4  

In [25]:
idx_6 = np.where(y_train == '6')
idx_9 = np.where(y_train == '9')

X_6 = X_train[idx_6]
X_9 = X_train[idx_9]

y_6 = y_train[idx_6]
y_9 = y_train[idx_9]

X_6_9_stack = np.concatenate((X_6, X_9), axis=0)
y_6_9_stack = np.concatenate((y_6, y_9), axis=0)

In [28]:
from sklearn.utils import shuffle

X_6_9_shuffled = shuffle(X_6_9_stack, random_state=1729)
y_6_9_shuffled = shuffle(y_6_9_stack, random_state=1729)
# y_6_9_shuffled[:3]

y_new = np.where(y_6_9_shuffled == '6', 1, -1)
y_new[:3]

array([ 1, -1, -1])

# Q5  

In [52]:
from sklearn.linear_model import Perceptron
perceptron = Perceptron(eta0=1, random_state=1729, max_iter=10, shuffle=False, fit_intercept=True)
perceptron.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,


Perceptron(eta0=1, max_iter=10, random_state=1729, shuffle=False)

In [53]:
perceptron.n_iter_

10

In [54]:
perceptron.coef_.shape

(10, 784)

In [60]:
perceptron.coef_[][68]

IndexError: ignored

In [62]:
from sklearn.linear_model import Perceptron
perceptron = Perceptron(warm_start=True, eta0=1, random_state=1729, max_iter=5, shuffle=False, fit_intercept=True)
intercepts = []
for i in range(5):
  perceptron.fit(X_train, y_train)
  intercepts.append(perceptron.intercept_)
intercepts

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_mo

[array([ -379.,  -144.,  -386.,  -965.,  -229.,   341.,  -401.,   -24.,
        -2408., -1239.]),
 array([ -379.,  -144.,  -386.,  -965.,  -229.,   341.,  -401.,   -24.,
        -2408., -1239.]),
 array([ -379.,  -144.,  -386.,  -965.,  -229.,   341.,  -401.,   -24.,
        -2408., -1239.]),
 array([ -379.,  -144.,  -386.,  -965.,  -229.,   341.,  -401.,   -24.,
        -2408., -1239.]),
 array([ -379.,  -144.,  -386.,  -965.,  -229.,   341.,  -401.,   -24.,
        -2408., -1239.])]