# AQ 7.4  

## Q6  

In [32]:
import numpy as np
r = np.array([7, 16])
b = np.array([9, 11])
new = np.array([9, 14])

dr = np.sum((r-new)**2)
db = np.sum((b-new)**2)

print(dr, db)

8 9


## Q7  

In [33]:
import numpy as np
x = np.array([[1000,0.5],
                [2000, 0.6],
                [1500, 0.3],
                [990, 1.0],
                [5400, 0.7]])
y = np.array([11, 20, 42, 16, 25])

print(x.shape, y.shape)

(5, 2) (5,)


In [34]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor

In [35]:
# print(help(KNeighborsRegressor))

In [36]:
mms = MinMaxScaler()
x_transformed = mms.fit_transform(x)

knn_reg = KNeighborsRegressor(n_neighbors=3, metric='euclidean')
knn_reg.fit(x_transformed, y)

KNeighborsRegressor(metric='euclidean', n_neighbors=3)

In [37]:
x_test = np.array([[1700, 0.2]])
print(x_test.shape)

(1, 2)


In [38]:
knn_reg.predict(x_test)

array([29.])

# AQ 7.5  

## Q12  

In [42]:
from sklearn.feature_extraction.text import HashingVectorizer
print(help(HashingVectorizer.build_analyzer))

Help on function build_analyzer in module sklearn.feature_extraction.text:

build_analyzer(self)
    Return a callable to process input data.
    
    The callable handles that handles preprocessing, tokenization, and
    n-grams generation.
    
    Returns
    -------
    analyzer: callable
        A function to handle preprocessing, tokenization
        and n-grams generation.

None


# AQ 9.4  

In [1]:
from sklearn.tree import DecisionTreeClassifier
?DecisionTreeClassifier

Init signature:
DecisionTreeClassifier(
    *,
    criterion='gini',
    splitter='best',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    class_weight=None,
    ccp_alpha=0.0,
)
Docstring:     
A decision tree classifier.

Read more in the :ref:`User Guide <tree>`.

Parameters
----------
criterion : {"gini", "entropy"}, default="gini"
    The function to measure the quality of a split. Supported criteria are
    "gini" for the Gini impurity and "entropy" for the information gain.

splitter : {"best", "random"}, default="best"
    The strategy used to choose the split at each node. Supported
    strategies are "best" to choose the best split and "random" to choose
    the best random split.

max_depth : int, default=None
    The maximum depth of the tree. If None, then nodes are expanded until
    all leaves are pure or until al

# AQ 12.1  

`Q6`  

In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=10, random_state=1)
X_t, X_test, y_t, y_test = train_test_split(X, y, stratify=y, random_state=1)
print(y_test)

[0 1 1]


In [2]:
clf = MLPClassifier(random_state=1).fit(X_t, y_t)
print(clf.predict(X_test))

[0 1 1]


In [3]:
clf.score(X_test, y_test)

1.0

`Q7`  

In [4]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
X, y = make_regression(n_samples=200, random_state=1)
regr = MLPRegressor(random_state=1, max_iter=500).fit(X, y)
print(regr.out_activation_)

identity


/home/ganesh/anaconda3/envs/sklearn-env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
