# MOCK OPE1  

In [279]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer

In [280]:
X, y = load_breast_cancer(as_frame=True, return_X_y=True)

In [281]:
X.shape

(569, 30)

In [282]:
y.shape

(569,)

In [283]:
data = load_breast_cancer()

In [284]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [285]:
print(np.unique(y))

[0 1]


In [286]:
y.value_counts()

1    357
0    212
Name: target, dtype: int64

In [287]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [288]:
X.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [289]:
X[['mean radius', 'mean perimeter']].corr()

mean radius  mean perimeter
mean radius        1.000000        0.997855
mean perimeter     0.997855        1.000000

## Q6  

In [290]:
a = np.array([[7,16,31],
            [np.nan, np.nan, 66],
            [12,5,np.nan],
            [98,np.nan,92]])
a

array([[ 7., 16., 31.],
       [nan, nan, 66.],
       [12.,  5., nan],
       [98., nan, 92.]])

In [291]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [292]:
imputer.fit_transform(a)

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

## Q7  

In [293]:
from sklearn.preprocessing import FunctionTransformer
log_transformer = FunctionTransformer(func=np.log10)

In [294]:
b = np.array([[1,1],
                [2,3],
                [10,100]])
b

array([[  1,   1],
       [  2,   3],
       [ 10, 100]])

In [295]:
log_transformer.fit_transform(b)

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])

## Q8  

In [296]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_li

In [297]:
names = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names=names)

In [298]:
df.head()

sepal length  sepal width  petal length  petal width        label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [299]:
df.shape

(150, 5)

In [300]:
from sklearn.preprocessing import PolynomialFeatures
poly_transform = PolynomialFeatures(degree=2)

In [301]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]
print(X.shape, y.shape)

(150, 4) (150,)


In [302]:
X_poly = poly_transform.fit_transform(X)
X_poly.shape

(150, 15)

## Q9  

In [303]:
from sklearn.datasets import fetch_california_housing
X, y = fetch_california_housing(return_X_y=True)
print(X.shape, y.shape)

(20640, 8) (20640,)


In [304]:
from sklearn.feature_selection import SelectPercentile

In [305]:
?SelectPercentile

Init signature:
SelectPercentile(
    score_func=<function f_classif at 0x7f92c8d89900>,
    *,
    percentile=10,
)
Docstring:     
Select features according to a percentile of the highest scores.

Read more in the :ref:`User Guide <univariate_feature_selection>`.

Parameters
----------
score_func : callable, default=f_classif
    Function taking two arrays X and y, and returning a pair of arrays
    (scores, pvalues) or a single array with scores.
    Default is f_classif (see below "See Also"). The default function only
    works with classification tasks.

    .. versionadded:: 0.18

percentile : int, default=10
    Percent of features to keep.

Attributes
----------
scores_ : array-like of shape (n_features,)
    Scores of features.

pvalues_ : array-like of shape (n_features,)
    p-values of feature scores, None if `score_func` returned only scores.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of s

In [306]:
sp = SelectPercentile(percentile=10)
X_10 = sp.fit_transform(X, y)
X_10

array([[8.3252],
       [8.3014],
       [7.2574],
       ...,
       [1.7   ],
       [1.8672],
       [2.3886]])

In [307]:
X_10.shape

(20640, 1)

## Q10  

In [308]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

X, y = fetch_california_housing(return_X_y=True)

print(type(X), type(y))
print(X.shape, y.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(20640, 8) (20640,)


In [309]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape

(16512, 8)

## Q11  

In [310]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [311]:
from sklearn.dummy import DummyRegressor
dummy_mean = DummyRegressor(strategy="mean")
dummy_mean.fit(X_train, y_train)
y_pred = dummy_mean.predict(X_test)
y_pred

array([2.07324883, 2.07324883, 2.07324883, ..., 2.07324883, 2.07324883,
       2.07324883])

In [312]:
assert y_test.shape == y_pred.shape

In [313]:
print(y_test.shape, y_pred.shape)

(4128,) (4128,)


In [314]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.0004196068688417931

In [315]:
# from sklearn.dummy import DummyRegressor
# dummy_mean = DummyRegressor(strategy="mean")
# dummy_mean.fit(X, y)
# y_pred = dummy_mean.predict(X)
# y_pred.shape

In [316]:
# from sklearn.metrics import r2_score
# r2_score(y, y_pred)

## Q12   

In [317]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import Pipeline

scaler = MinMaxScaler()
sgdr = SGDRegressor()
sgd_pipe = Pipeline([('scaler', scaler),
                    ('sgd_regressor', sgdr)])

In [318]:
sgd_pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('sgd_regressor', SGDRegressor())])

In [319]:
from sklearn.metrics import mean_absolute_error
mae_training = mean_absolute_error(y_train, sgd_pipe.predict(X_train))
mae_training

0.5637028394576281

## Q13  

In [320]:
mae_test = mean_absolute_error(y_test, sgd_pipe.predict(X_test))
mae_test

0.5565139624974021

## Q14  

In [321]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()
cvs = cross_val_score(lin_reg, X, y, cv=5)
cvs

array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

## Q15  

In [322]:
from sklearn.datasets import load_diabetes
data = load_diabetes()
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [323]:
data.data.shape

(442, 10)

In [324]:
data.target.shape

(442,)

## Q16  

In [ ]:
X = data.data
X.shape, type(X)

((442, 10), numpy.ndarray)

In [ ]:
y = data.target
y.shape, type(y)

((442,), numpy.ndarray)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [ ]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(353, 10) (353,)
(89, 10) (89,)


In [ ]:
ss = StandardScaler()
lr = LinearRegression()

lr_pipe = Pipeline([('scaler', ss),
                    ('linear_reg', lr)])

In [ ]:
lr_pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_reg', LinearRegression())])

In [ ]:
lr_pipe.score(X_test, y_test)

0.5341988244945843

## Q17  

In [ ]:
data.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [ ]:
s3 = data.feature_names.index('s3')
s3

6

In [ ]:
lr.coef_

array([ -0.1850394 , -10.74378586,  23.97110665,  15.4460079 ,
       -33.6348803 ,  19.07653925,   3.87696491,  10.51802947,
        34.1537076 ,   1.91366485])

In [ ]:
lr.coef_[s3]

3.8769649104866417

## Q18  

In [ ]:
?RidgeCV

In [ ]:
cv=5
alphas = np.logspace(-4, 0, num=20)
scoring = 'neg_mean_absolute_error'

# type(alphas)

In [ ]:
from sklearn.linear_model import RidgeCV

ridge_cv = RidgeCV(alphas=alphas, cv=cv, scoring=scoring)

In [ ]:
ridge_cv.fit(X_train, y_train)

RidgeCV(alphas=array([1.00000000e-04, 1.62377674e-04, 2.63665090e-04, 4.28133240e-04,
       6.95192796e-04, 1.12883789e-03, 1.83298071e-03, 2.97635144e-03,
       4.83293024e-03, 7.84759970e-03, 1.27427499e-02, 2.06913808e-02,
       3.35981829e-02, 5.45559478e-02, 8.85866790e-02, 1.43844989e-01,
       2.33572147e-01, 3.79269019e-01, 6.15848211e-01, 1.00000000e+00]),
        cv=5, scoring='neg_mean_absolute_error')

In [ ]:
best_mae = -1 * ridge_cv.best_score_
best_mae

45.143016100985086