# MOCK OPE1  

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer

In [ ]:
X, y = load_breast_cancer(as_frame=True, return_X_y=True)

In [ ]:
X.shape

In [ ]:
y.shape

In [ ]:
data = load_breast_cancer()

In [ ]:
print(data.DESCR)

In [ ]:
print(np.unique(y))

In [ ]:
y.value_counts()

In [ ]:
X.info()

In [13]:
X.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [16]:
X[['mean radius', 'mean perimeter']].corr()

mean radius  mean perimeter
mean radius        1.000000        0.997855
mean perimeter     0.997855        1.000000

## Q6  

In [17]:
a = np.array([[7,16,31],
            [np.nan, np.nan, 66],
            [12,5,np.nan],
            [98,np.nan,92]])
a

array([[ 7., 16., 31.],
       [nan, nan, 66.],
       [12.,  5., nan],
       [98., nan, 92.]])

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [20]:
imputer.fit_transform(a)

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

## Q7  

In [21]:
from sklearn.preprocessing import FunctionTransformer
log_transformer = FunctionTransformer(func=np.log10)

In [22]:
b = np.array([[1,1],
                [2,3],
                [10,100]])
b

array([[  1,   1],
       [  2,   3],
       [ 10, 100]])

In [23]:
log_transformer.fit_transform(b)

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])

## Q8  

In [36]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_li

In [37]:
names = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names=names)

In [38]:
df.head()

sepal length  sepal width  petal length  petal width        label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [39]:
df.shape

(150, 5)

In [40]:
from sklearn.preprocessing import PolynomialFeatures
poly_transform = PolynomialFeatures(degree=2)

In [43]:
X, y = df.iloc[:, :-1], df.iloc[:, -1]
print(X.shape, y.shape)

(150, 4) (150,)


In [46]:
X_poly = poly_transform.fit_transform(X)
X_poly.shape

(150, 15)

## Q9  

In [47]:
from sklearn.datasets import fetch_california_housing
X, y = fetch_california_housing(return_X_y=True)
print(X.shape, y.shape)

(20640, 8) (20640,)


In [49]:
from sklearn.feature_selection import SelectPercentile

In [ ]:
?SelectPercentile

In [54]:
sp = SelectPercentile(percentile=10)
X_10 = sp.fit_transform(X, y)
X_10

array([[8.3252],
       [8.3014],
       [7.2574],
       ...,
       [1.7   ],
       [1.8672],
       [2.3886]])

In [55]:
X_10.shape

(20640, 1)

## Q10  

In [57]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

X, y = fetch_california_housing(return_X_y=True)

print(type(X), type(y))
print(X.shape, y.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(20640, 8) (20640,)


In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape

(16512, 8)

## Q11  

In [84]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [85]:
from sklearn.dummy import DummyRegressor
dummy_mean = DummyRegressor(strategy="mean")
dummy_mean.fit(X_train, y_train)
y_pred = dummy_mean.predict(X_test)
y_pred

array([2.06593589, 2.06593589, 2.06593589, ..., 2.06593589, 2.06593589,
       2.06593589])

In [86]:
assert y_test.shape == y_pred.shape

In [87]:
print(y_test.shape, y_pred.shape)

(4128,) (4128,)


In [88]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.0001229388790742192

In [89]:
# from sklearn.dummy import DummyRegressor
# dummy_mean = DummyRegressor(strategy="mean")
# dummy_mean.fit(X, y)
# y_pred = dummy_mean.predict(X)
# y_pred.shape

In [90]:
# from sklearn.metrics import r2_score
# r2_score(y, y_pred)

## Q12   

In [91]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import Pipeline

scaler = MinMaxScaler()
sgdr = SGDRegressor()
sgd_pipe = Pipeline([('scaler', scaler),
                    ('sgd_regressor', sgdr)])

In [93]:
sgd_pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('sgd_regressor', SGDRegressor())])

In [98]:
from sklearn.metrics import mean_absolute_error
mae_training = mean_absolute_error(y_train, sgd_pipe.predict(X_train))
mae_training

0.5540735850057835

## Q13  

In [99]:
mae_test = mean_absolute_error(y_test, sgd_pipe.predict(X_test))
mae_test

0.5755694413271141

## Q14  

In [101]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()
cvs = cross_val_score(lin_reg, X, y, cv=5)
cvs

array([0.54866323, 0.46820691, 0.55078434, 0.53698703, 0.66051406])

## Q15  

In [ ]:
from sklearn.datasets import load_diabetes
data = load_diabetes()
print(data.DESCR)

In [110]:
data.data.shape

(442, 10)

In [111]:
data.target.shape

(442,)

## Q16  

In [113]:
X = data.data
X.shape, type(X)

((442, 10), numpy.ndarray)

In [114]:
y = data.target
y.shape, type(y)

((442,), numpy.ndarray)