In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, classification_report, confusion_matrix, accuracy_score, f1_score

print("Import succesfull")

Import succesfull


In [2]:
X = np.array(list(range(1, 11))).reshape(-1,1)
y = np.array([(11*i)+1 for i in range(1, 11)]).reshape(-1,1)
X, y

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[ 12],
        [ 23],
        [ 34],
        [ 45],
        [ 56],
        [ 67],
        [ 78],
        [ 89],
        [100],
        [111]]))

In [3]:
df = pd.DataFrame(zip(X, y), columns=['ind', 'label'])
df

ind  label
0   [1]   [12]
1   [2]   [23]
2   [3]   [34]
3   [4]   [45]
4   [5]   [56]
5   [6]   [67]
6   [7]   [78]
7   [8]   [89]
8   [9]  [100]
9  [10]  [111]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((7, 1), (7, 1), (3, 1), (3, 1))

In [5]:
X_train, X_test, y_train, y_test 

(array([[ 1],
        [ 8],
        [ 3],
        [10],
        [ 5],
        [ 4],
        [ 7]]),
 array([[9],
        [2],
        [6]]),
 array([[ 12],
        [ 89],
        [ 34],
        [111],
        [ 56],
        [ 45],
        [ 78]]),
 array([[100],
        [ 23],
        [ 67]]))

In [6]:
linear_model = LinearRegression()
linear_model

LinearRegression()

In [7]:
linear_model.fit(X_train, y_train)

LinearRegression()

In [8]:
y_pred = linear_model.predict(X_test)
y_pred

array([[100.],
       [ 23.],
       [ 67.]])

In [9]:
y_test

array([[100],
       [ 23],
       [ 67]])

In [10]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred)

(3.7865323450608567e-29, 3.552713678800501e-15)

In [11]:
linear_model.coef_[0], linear_model.intercept_[0]

(array([11.]), 0.9999999999999858)

In [12]:
linear_model.n_features_in_

1

In [13]:
linear_model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

In [14]:
linear_model.score(X_train, y_train)

1.0