# GA5 practice for OPPE2  

In [2]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.datasets import fetch_openml
data = fetch_openml('mnist_784', version=1)
type(data)

sklearn.utils.Bunch

In [3]:
X = data.data.to_numpy()
y = data.target.to_numpy()

X.shape, y.shape

((70000, 784), (70000,))

In [4]:
X_train, X_test = X[:10000], X[10000:12000]
y_train, y_test = y[:10000], y[10000:12000]

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((10000, 784), (2000, 784), (10000,), (2000,))

In [9]:
idx_5 = np.where(y_train == '5')
idx_3 = np.where(y_train == '3')

X_5 = X_train[idx_5]
X_3 = X_train[idx_3]

y_5 = y_train[idx_5]
y_3 = y_train[idx_3]

X_5_3_stacked = np.concatenate((X_5, X_3), axis = 0)
y_5_3_stacked = np.concatenate((y_5, y_3), axis = 0)

X_5_3_stacked.shape, y_5_3_stacked.shape

((1895, 784), (1895,))

In [14]:
y_new = np.where(y_5_3_stacked=='5', 1, -1)
print(y_new)
print(y_new[:5])
print(y_new[-5:])

[ 1  1  1 ... -1 -1 -1]
[1 1 1 1 1]
[-1 -1 -1 -1 -1]


In [28]:
from sklearn.linear_model import Perceptron
pcpc = Perceptron(alpha=1, max_iter=100, shuffle=True, fit_intercept=True, penalty=None, random_state=42)
pcpc

Perceptron(alpha=1, max_iter=100, random_state=42)

In [29]:
pcpc.fit(X_5_3_stacked, y_new)

Perceptron(alpha=1, max_iter=100, random_state=42)

In [30]:
len(X_5), len(X_3)

(863, 1032)

In [31]:
idx_5_test = np.where(y_test == '5')
idx_3_test = np.where(y_test == '3')

X_5_test = X_test[idx_5_test]
X_3_test = X_test[idx_3_test]

y_5_test = y_test[idx_5_test]
y_3_test = y_test[idx_3_test]

X_5_3_stacked_test = np.concatenate((X_5_test, X_3_test), axis = 0)
y_5_3_stacked_test = np.concatenate((y_5_test, y_3_test), axis = 0)

X_5_3_stacked_test.shape, y_5_3_stacked_test.shape

((381, 784), (381,))

In [32]:
y_test_new = np.where(y_5_3_stacked_test=='5', 1, -1)
len(y_test_new)

381

In [33]:
y_test_new[:5], y_test_new[-5:]

(array([1, 1, 1, 1, 1]), array([-1, -1, -1, -1, -1]))

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_new, pcpc.predict(X_5_3_stacked_test))
cm

array([[190,   6],
       [ 12, 173]], dtype=int64)

In [40]:
from matplotlib.pyplot import cla
from sklearn.metrics import classification_report
cr = classification_report(y_test_new, pcpc.predict(X_5_3_stacked_test))
print(cr)

              precision    recall  f1-score   support

          -1       0.94      0.97      0.95       196
           1       0.97      0.94      0.95       185

    accuracy                           0.95       381
   macro avg       0.95      0.95      0.95       381
weighted avg       0.95      0.95      0.95       381



In [35]:
pcpc_6 = Perceptron(alpha=1, 
                    max_iter=100, 
                    shuffle=False, 
                    fit_intercept=True, 
                    penalty=None, 
                    random_state=42)
pcpc_6.fit(X_5_3_stacked, y_new)

Perceptron(alpha=1, max_iter=100, random_state=42, shuffle=False)

In [36]:
from sklearn.metrics import confusion_matrix
cm6 = confusion_matrix(y_test_new, pcpc_6.predict(X_5_3_stacked_test))
cm6

array([[196,   0],
       [172,  13]], dtype=int64)

In [41]:
cr6 = classification_report(y_test_new, pcpc_6.predict(X_5_3_stacked_test))
print(cr6)

              precision    recall  f1-score   support

          -1       0.53      1.00      0.70       196
           1       1.00      0.07      0.13       185

    accuracy                           0.55       381
   macro avg       0.77      0.54      0.41       381
weighted avg       0.76      0.55      0.42       381



For remaining questions, see ga5_mlp.ipynb file in 'graded' github repo.  