# PA5 practice for OPPE2  

In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.datasets import fetch_openml
data = fetch_openml('mnist_784', version='1')
type(data)

sklearn.utils.Bunch

In [5]:
data.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [6]:
data.data.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [7]:
data.target.head()

0    5
1    0
2    4
3    1
4    9
Name: class, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [8]:
data.data.shape

(70000, 784)

In [9]:
X = data.data
y = data.target
X.shape, y.shape

((70000, 784), (70000,))

In [10]:
type(X)

pandas.core.frame.DataFrame

In [11]:
y[2022], X.iloc[2022].mean(), X.iloc[2022].T.value_counts()

('2',
 27.761479591836736,
 0.0      643
 254.0     32
 6.0        5
 60.0       4
 227.0      4
         ... 
 225.0      1
 2.0        1
 133.0      1
 224.0      1
 72.0       1
 Name: 2022, Length: 74, dtype: int64)

In [12]:
X = X.to_numpy()
y = y.to_numpy()

In [13]:
X_train, X_test = X[:10000], X[10000:12000]
y_train, y_test = y[:10000], y[10000:12000]
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((10000, 784), (2000, 784), (10000,), (2000,))

In [14]:
len(np.unique(y_train)), np.count_nonzero(y_train == "6"), np.count_nonzero(y_train == "9"), len(np.unique(y_test)), np.unique(y_test, return_counts=True)

(10,
 1014,
 978,
 10,
 (array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype=object),
  array([205, 224, 185, 196, 204, 185, 194, 209, 183, 215], dtype=int64)))

In [15]:
idx_6 = np.where(y_train == '6')
idx_9 = np.where(y_train == '9')

X_6 = X_train[idx_6]
X_9 = X_train[idx_9]

y_6 = y_train[idx_6]
y_9 = y_train[idx_9]

X_6_9_stack = np.concatenate((X_6, X_9), axis=0)
y_6_9_stack = np.concatenate((y_6, y_9), axis=0)

In [16]:
from sklearn.utils import shuffle

X_6_9_shuffled = shuffle(X_6_9_stack, random_state=1729)
y_6_9_shuffled = shuffle(y_6_9_stack, random_state=1729)

y_new = np.where(y_6_9_shuffled == '6', 1, -1)
y_new[:3]

array([ 1, -1, -1])

In [17]:
from sklearn.linear_model import Perceptron
pcpc = Perceptron(alpha=1, max_iter=10, shuffle=False, fit_intercept=True, penalty=None, random_state=1729)
pcpc

Perceptron(alpha=1, max_iter=10, random_state=1729, shuffle=False)

In [18]:
pcpc.fit(X_6_9_shuffled, y_new)

c:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:696: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


Perceptron(alpha=1, max_iter=10, random_state=1729, shuffle=False)

In [19]:
pcpc.n_iter_

10

In [20]:
pcpc.coef_.shape

(1, 784)

In [21]:
pcpc.coef_[9][68]

IndexError: index 9 is out of bounds for axis 0 with size 1

In [ ]:
pcpc.intercept_

array([ -190.,   -70.,  -169.,  -418.,  -109.,   160.,  -182.,    -4.,
       -1025.,  -539.])

In [ ]:
?pcpc

Type:        Perceptron
String form: Perceptron(alpha=1, max_iter=10, random_state=1729, shuffle=False)
File:        c:\programdata\anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_perceptron.py
Docstring:  
Linear perceptron classifier.

Read more in the :ref:`User Guide <perceptron>`.

Parameters
----------

penalty : {'l2','l1','elasticnet'}, default=None
    The penalty (aka regularization term) to be used.

alpha : float, default=0.0001
    Constant that multiplies the regularization term if regularization is
    used.

l1_ratio : float, default=0.15
    The Elastic Net mixing parameter, with `0 <= l1_ratio <= 1`.
    `l1_ratio=0` corresponds to L2 penalty, `l1_ratio=1` to L1.
    Only used if `penalty='elasticnet'`.

    .. versionadded:: 0.24

fit_intercept : bool, default=True
    Whether the intercept should be estimated or not. If False, the
    data is assumed to be already centered.

max_iter : int, default=1000
    The maximum number of passes over the training da