# PA7 practice for OPPE2  

In [34]:
import numpy as np
import pandas as pd

`Q1-3`  

In [1]:
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cvt = CountVectorizer()

In [4]:
x = cvt.fit_transform(text_data)
x.shape

(9, 99)

In [ ]:
?cvt

In [6]:
cvt2 = CountVectorizer(min_df=2)
x2 = cvt2.fit_transform(text_data)
x2.shape

(9, 20)

In [10]:
type(cvt.vocabulary_)

dict

In [11]:
# cvt.vocabulary_
cvt.vocabulary_['metaverse']

51

`Q4`  

In [12]:
Docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cvt4 = CountVectorizer(max_features=10)

In [25]:
x4 = cvt4.fit_transform(Docs)
x4

<3x10 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [26]:
type(x4)

scipy.sparse.csr.csr_matrix

In [ ]:
?x4

In [27]:
x4.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1]], dtype=int64)

`Q5, 6`  

`Could not solve`  

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier
?knn

`Q7`  

In [31]:
from sklearn.datasets import load_digits
X, y = load_digits(return_X_y=True)
X.shape, y.shape

((1797, 64), (1797,))

In [36]:

len(np.unique(y))

10

In [43]:
counts = np.unique(y, return_counts=True)
counts

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180], dtype=int64))

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1437, 64), (360, 64), (1437,), (360,))

`Note: Pipeline method and fit_transform/transform give same result. However, fit_transform/fit_transform gives the correct answer!`  

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

ss = StandardScaler()
log_reg = LogisticRegression(multi_class='multinomial', solver='sag')
pipe = Pipeline([('scaler', ss),
                ('clf', log_reg)])

In [47]:
pipe.fit(X_train, y_train)

c:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Pipeline(steps=[('scaler', StandardScaler()),
                ('clf',
                 LogisticRegression(multi_class='multinomial', solver='sag'))])

In [49]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, pipe.predict(X_test))
score

0.9666666666666667

In [50]:
X_train_tf = ss.fit_transform(X_train)
log_reg.fit(X_train_tf, y_train)

c:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(multi_class='multinomial', solver='sag')

`The following method gives the correct answer`  

In [52]:
X_test_tf = ss.fit_transform(X_test)
y_pred = log_reg.predict(X_test_tf)

accuracy_score(y_test, y_pred)

0.9694444444444444

In [54]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted')

0.96954657886119

`Can also use classification report`  

In [56]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.97      0.97        34
           2       0.94      1.00      0.97        34
           3       1.00      0.95      0.97        40
           4       0.97      0.94      0.96        34
           5       0.94      1.00      0.97        32
           6       0.97      0.97      0.97        37
           7       1.00      1.00      1.00        40
           8       0.88      0.91      0.90        33
           9       1.00      0.95      0.97        39

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360

